spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
app.jwt.secret=${JWT_SECRET}
server.servlet.context-path=/pet-sitter
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
