spring.application.name=pet-sitter
spring.datasource.url=jdbc:postgresql://localhost:5432/pet_sitter_db
spring.datasource.username=serotonine
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port = 8085
spring.jackson.time-zone=Europe/Brussels
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
# spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false?
