spring.profiles.active=dev
spring.application.name=pet-sitter
spring.datasource.username=serotonine
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.time-zone=Europe/Brussels
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
